substitutions:
  devicename: "kincony-a16"
  friendly_name: "Kincony A16 Controller"

esphome:
  name: kc868-a16-a
  friendly_name: KC868-A16-A
  project:
    name: "kincony.kc868-a16"
    version: "1.1"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
# Логирование (через Serial и WiFi/Ethernet)
logger:
  level: DEBUG

# API для связи с Home Assistant
api:
  encryption:
    key: !secret api_encryption_key
    
# Обновление "по воздуху"
ota:
  - platform: esphome
    password: !secret ota_password

# --- НАСТРОЙКА СЕТИ (ETHERNET) ---
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  
  clk: 
    pin: GPIO17 
    mode: CLK_OUT
  
  phy_addr: 0
  power_pin: GPIO0
  
  manual_ip: 
    static_ip: 192.168.0.99 
    gateway: 192.168.0.1    
    subnet: 255.255.255.0

# --- I2C ШИНА (КРИТИЧЕСКИ ВАЖНО) ---
# KC868-A16 использует I2C для управления реле и входами
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true # При старте в логах покажет найденные устройства
  id: bus_a

# Рекомендуется также добавить веб-сервер, чтобы видеть состояние
# устройства в браузере по его IP, даже когда все работает нормально
web_server:
  port: 80
    

# --- КОМПОНЕНТЫ РАСШИРИТЕЛЕЙ (PCF8574) ---
# Адреса могут быть 0x21, 0x22, 0x23, 0x24, 0x25, 0x26.
# Проверьте логи после прошивки, если не работает.

# Чип для ВХОДОВ 1-8
pcf8574:
  - id: 'pcf8574_inputs_1_8'
    i2c_id: bus_a
    address: 0x21 # Стандартный адрес для входов 1-8
    pcf8575: false

  # Чип для ВХОДОВ 9-16
  - id: 'pcf8574_inputs_9_16'
    i2c_id: bus_a
    address: 0x22 # Стандартный адрес для входов 9-16
    pcf8575: false

  # Чип для РЕЛЕ 1-8
  - id: 'pcf8574_relays_1_8'
    i2c_id: bus_a
    address: 0x24 # Стандартный адрес для реле 1-8
    pcf8575: false

  # Чип для РЕЛЕ 9-16
  - id: 'pcf8574_relays_9_16'
    i2c_id: bus_a
    address: 0x25 # Стандартный адрес для реле 9-16
    pcf8575: false

# --- РЕЛЕ (SWITCHES) ---
switch:
  - platform: gpio
    name: "Relay 1"
    id: "Relay_1_id"
    pin:
      pcf8574: pcf8574_relays_1_8
      number: 0
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Relay 2"
    id: "Relay_2_id"
    pin:
      pcf8574: pcf8574_relays_1_8
      number: 1
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Relay 3"
    id: "Relay_3_id"
    pin:
      pcf8574: pcf8574_relays_1_8
      number: 2
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Relay 4"
    id: "Relay_4_id"
    pin:
      pcf8574: pcf8574_relays_1_8
      number: 3
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Relay 5"
    id: "Relay_5_id"
    pin:
      pcf8574: pcf8574_relays_1_8
      number: 4
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Relay 6"
    id: "Relay_6_id"
    pin:
      pcf8574: pcf8574_relays_1_8
      number: 5
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Relay 7"
    id: "Relay_7_id"
    pin:
      pcf8574: pcf8574_relays_1_8
      number: 6
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Relay 8"
    id: "Relay_8_id"
    pin:
      pcf8574: pcf8574_relays_1_8
      number: 7
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF   

  # Вторая группа реле (9-16)
  - platform: gpio
    name: "Relay 9"
    id: "Relay_9_id"
    pin:
      pcf8574: pcf8574_relays_9_16
      number: 0
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Relay 10"
    id: "Relay_10_id"
    pin:
      pcf8574: pcf8574_relays_9_16
      number: 1
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Relay 11"
    id: "Relay_11_id"
    pin:
      pcf8574: pcf8574_relays_9_16
      number: 2
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Relay 12"
    id: "Relay_12_id"
    pin:
      pcf8574: pcf8574_relays_9_16
      number: 3
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Relay 13"
    id: "Relay_13_id"
    pin:
      pcf8574: pcf8574_relays_9_16
      number: 4
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Relay 14"
    id: "Relay_14_id"
    pin:
      pcf8574: pcf8574_relays_9_16
      number: 5
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Relay 15"
    id: "Relay_15_id"
    pin:
      pcf8574: pcf8574_relays_9_16
      number: 6
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Relay 16"
    id: "Relay_16_id"
    pin:
      pcf8574: pcf8574_relays_9_16
      number: 7
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF

# --- ЦИФРОВЫЕ ВХОДЫ (BINARY SENSORS) ---
binary_sensor:
  - platform: gpio
    name: "Input 1"
    pin:
      pcf8574: pcf8574_inputs_1_8
      number: 0
      mode: INPUT
      inverted: false # Входы обычно замыкаются на землю (GND)
    on_press:
      then:
        # switch.toggle переключает Relay 1 (вкл -> выкл, выкл -> вкл)
        - switch.toggle: Relay_1_id
  - platform: gpio
    name: "Input 2"
    pin:
      pcf8574: pcf8574_inputs_1_8
      number: 1
      mode: INPUT
      inverted: false
    on_press:
      then:
        - switch.toggle: Relay_2_id
  - platform: gpio
    name: "Input 3"
    pin:
      pcf8574: pcf8574_inputs_1_8
      number: 2
      mode: INPUT
      inverted: false
    on_press:
      then:
        - switch.toggle: Relay_3_id
  - platform: gpio
    name: "Input 4"
    pin:
      pcf8574: pcf8574_inputs_1_8
      number: 3
      mode: INPUT
      inverted: false
    on_press:
      then:
        - switch.toggle: Relay_4_id
  - platform: gpio
    name: "Input 5"
    pin:
      pcf8574: pcf8574_inputs_1_8
      number: 4
      mode: INPUT
      inverted: false
    on_press:
      then:
        - switch.toggle: Relay_5_id
  - platform: gpio
    name: "Input 6"
    pin:
      pcf8574: pcf8574_inputs_1_8
      number: 5
      mode: INPUT
      inverted: false
    on_press:
      then:
        - switch.toggle: Relay_6_id
  - platform: gpio
    name: "Input 7"
    pin:
      pcf8574: pcf8574_inputs_1_8
      number: 6
      mode: INPUT
      inverted: false
    on_press:
      then:
        - switch.toggle: Relay_7_id
  - platform: gpio
    name: "Input 8"
    pin:
      pcf8574: pcf8574_inputs_1_8
      number: 7
      mode: INPUT
      inverted: false
    on_press:
      then:
        - switch.toggle: Relay_8_id      

  # Вторая группа входов (9-16)
  - platform: gpio
    name: "Input 9"
    pin:
      pcf8574: pcf8574_inputs_9_16
      number: 0
      mode: INPUT
      inverted: false
    on_press:
      then:
        - switch.toggle: Relay_9_id
  - platform: gpio
    name: "Input 10"
    pin:
      pcf8574: pcf8574_inputs_9_16
      number: 1
      mode: INPUT
      inverted: false
    on_press:
      then:
        - switch.toggle: Relay_10_id
  - platform: gpio
    name: "Input 11"
    pin:
      pcf8574: pcf8574_inputs_9_16
      number: 2
      mode: INPUT
      inverted: false
    on_press:
      then:
        - switch.toggle: Relay_11_id
  - platform: gpio
    name: "Input 12"
    pin:
      pcf8574: pcf8574_inputs_9_16
      number: 3
      mode: INPUT
      inverted: false
    on_press:
      then:
        - switch.toggle: Relay_12_id
  - platform: gpio
    name: "Input 13"
    pin:
      pcf8574: pcf8574_inputs_9_16
      number: 4
      mode: INPUT
      inverted: false
    on_press:
      then:
        - switch.toggle: Relay_13_id
  - platform: gpio
    name: "Input 14"
    pin:
      pcf8574: pcf8574_inputs_9_16
      number: 5
      mode: INPUT
      inverted: false
    on_press:
      then:
        - switch.toggle: Relay_14_id
  - platform: gpio
    name: "Input 15"
    pin:
      pcf8574: pcf8574_inputs_9_16
      number: 6
      mode: INPUT
      inverted: false
    on_press:
      then:
        - switch.toggle: Relay_15_id
  - platform: gpio
    name: "Input 16"
    pin:
      pcf8574: pcf8574_inputs_9_16
      number: 7
      mode: INPUT
      inverted: false
    on_press:
      then:
        - switch.toggle: Relay_16_id  

# --- ОПИСЫВАЕМ GPIO14 КАК ОБЩИЙ ВХОД (Binary Sensor) ДЛЯ ZERO-CROSS ---
  - platform: gpio
    name: "Zero Cross Input"
    pin: &zero_cross_pin
      number: GPIO14
      mode:
        input: true
        pullup: false  
        pulldown: true
      allow_other_uses: true
    id: zc_pin_id
    internal: true

# --- УПРАВЛЕНИЕ ДИММЕРОМ ROBOTDYN (4 КАНАЛА) ---
output:
  # Канал 1
  - platform: ac_dimmer
    id: dimmer_output_1
    gate_pin: GPIO32
    zero_cross_pin: *zero_cross_pin

  # Канал 2
  - platform: ac_dimmer
    id: dimmer_output_2
    gate_pin: GPIO33
    zero_cross_pin: *zero_cross_pin
    
  # Канал 3 (Пин RF передатчика)
  - platform: ac_dimmer
    id: dimmer_output_3
    gate_pin: GPIO15
    zero_cross_pin: *zero_cross_pin
    
  # Канал 4 (Пин RF приемника)
  - platform: ac_dimmer
    id: dimmer_output_4
    gate_pin: GPIO2
    zero_cross_pin: *zero_cross_pin

# Создаем сущности "Свет" для Home Assistant
light:
  - platform: monochromatic
    name: "Свет Комната 1"
    output: dimmer_output_1
    default_transition_length: 1s
    
  - platform: monochromatic
    name: "Свет Комната 2"
    output: dimmer_output_2
    default_transition_length: 1s

  - platform: monochromatic
    name: "Свет Комната 3"
    output: dimmer_output_3
    default_transition_length: 1s

  - platform: monochromatic
    name: "Свет Комната 4"
    output: dimmer_output_4
    default_transition_length: 1s